FROM ruby:3.3

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      default-mysql-client \
      libmariadb-dev \
      nodejs \
    && rm -rf /var/lib/apt/lists/*

ENV BUNDLE_PATH=/usr/local/bundle
ENV PATH="/usr/local/bundle/bin:$PATH"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
